// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5DUC0guBGp9XtAIVeWKvX-b1wBEXo8ls',
    appId: '1:430424752509:web:08c4171d000d3001858c14',
    messagingSenderId: '430424752509',
    projectId: 'badminfinder',
    authDomain: 'badminfinder.firebaseapp.com',
    storageBucket: 'badminfinder.firebasestorage.app',
    measurementId: 'G-69B26R7FR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv35r9sxft6nk_CvDrE4SFoCDA-Vz9ano',
    appId: '1:430424752509:android:4aa084b17f0c0157858c14',
    messagingSenderId: '430424752509',
    projectId: 'badminfinder',
    storageBucket: 'badminfinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0CLWcQmGcsvMXUagoWLtkVh1OmlkKnTA',
    appId: '1:430424752509:ios:b98ea0d045229f81858c14',
    messagingSenderId: '430424752509',
    projectId: 'badminfinder',
    storageBucket: 'badminfinder.firebasestorage.app',
    iosBundleId: 'com.teamtrow.victor',
  );
}
